package define

const (
	APPCLIENT_VERSIONS = "2.34.1"

	APPCLIENT_TYPE_IOS       = "1"
	APPCLIENT_TYPE_ANDROID   = "2"
	APPCLIENT_TYPE_WEBPC     = "4"
	APPCLIENT_TYPE_WEBMOBILE = "5"
)

const (
	// FORUMID_GENSHI 为原神分区
	FORUMID_GENSHI = "26"

	// FORUMID_BH2 为崩坏2分区
	FORUMID_BH2 = "30"

	// FORUMID_BH3 为崩坏3分区
	FORUMID_BH3 = "1"

	// FORUMID_WD 为未定事件簿分区
	FORUMID_WD = "37"

	// FORUMID_DBY 为大别野分区
	FORUMID_DBY = "34"

	// FORUMID_SR 为崩坏：星穹铁道区
	FORUMID_SR = "52"

	// FORUMID_ZZZ 为绝区零分区
	FORUMID_ZZZ = "57"
)
